import { getRem ,scaleByHeight} from '@/utils/function/function'
export const mockDataScreen = {
  status: '200',
  result: {
    current_page: 1,
    data: [
      {
        ccid: 'JL2100EF54917F100E49',
        high_heartrate_value: 130,
        low_heartrate_value: 40,
        spo2: 92,
        patient_id: 2,
        name: '123444',
        bed_number: '002',
        bat: 21,
        bind_time: 1760943565,
        bind_date: '2025/10/20 14:59 绑定',
        list: [
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764138392,
            insert_date: '2025-11-26 14',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764141992,
            insert_date: '2025-11-26 15',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764145592,
            insert_date: '2025-11-26 16',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764149192,
            insert_date: '2025-11-26 17',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764152792,
            insert_date: '2025-11-26 18',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764156392,
            insert_date: '2025-11-26 19',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764159992,
            insert_date: '2025-11-26 20',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764163592,
            insert_date: '2025-11-26 21',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764167192,
            insert_date: '2025-11-26 22',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764170792,
            insert_date: '2025-11-26 23',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764174392,
            insert_date: '2025-11-27 00',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764177992,
            insert_date: '2025-11-27 01',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764181592,
            insert_date: '2025-11-27 02',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764185192,
            insert_date: '2025-11-27 03',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764188792,
            insert_date: '2025-11-27 04',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764192392,
            insert_date: '2025-11-27 05',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764195992,
            insert_date: '2025-11-27 06',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764199592,
            insert_date: '2025-11-27 07',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764203192,
            insert_date: '2025-11-27 08',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764206792,
            insert_date: '2025-11-27 09',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764210392,
            insert_date: '2025-11-27 10',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764213992,
            insert_date: '2025-11-27 11',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764217592,
            insert_date: '2025-11-27 12',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764221192,
            insert_date: '2025-11-27 13',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
        ],
      },
      {
        ccid: 'JL2B07E8E56B58D07E37',
        high_heartrate_value: 130,
        low_heartrate_value: 40,
        spo2: 92,
        patient_id: 5,
        name: 'dasda',
        bed_number: '003',
        bat: 91,
        bind_time: 1762331543,
        bind_date: '2025/11/05 16:32 绑定',
        list: [
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764138392,
            insert_date: '2025-11-26 14',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764141992,
            insert_date: '2025-11-26 15',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764145592,
            insert_date: '2025-11-26 16',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764149192,
            insert_date: '2025-11-26 17',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764152792,
            insert_date: '2025-11-26 18',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764156392,
            insert_date: '2025-11-26 19',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764159992,
            insert_date: '2025-11-26 20',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764163592,
            insert_date: '2025-11-26 21',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764167192,
            insert_date: '2025-11-26 22',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764170792,
            insert_date: '2025-11-26 23',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764174392,
            insert_date: '2025-11-27 00',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764177992,
            insert_date: '2025-11-27 01',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764181592,
            insert_date: '2025-11-27 02',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764185192,
            insert_date: '2025-11-27 03',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764188792,
            insert_date: '2025-11-27 04',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764192392,
            insert_date: '2025-11-27 05',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764195992,
            insert_date: '2025-11-27 06',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764199592,
            insert_date: '2025-11-27 07',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764203192,
            insert_date: '2025-11-27 08',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764206792,
            insert_date: '2025-11-27 09',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764210392,
            insert_date: '2025-11-27 10',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764213992,
            insert_date: '2025-11-27 11',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764217592,
            insert_date: '2025-11-27 12',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764221192,
            insert_date: '2025-11-27 13',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
        ],
      },
      {
        ccid: 'JL2E7D07BB3E47B7D888',
        high_heartrate_value: 130,
        low_heartrate_value: 40,
        spo2: 92,
        patient_id: 58,
        name: 'zc_test1',
        bed_number: null,
        bat: null,
        bind_time: 1764034846,
        bind_date: '2025/11/25 09:40 绑定',
        list: [
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764138392,
            insert_date: '2025-11-26 14',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764141992,
            insert_date: '2025-11-26 15',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764145592,
            insert_date: '2025-11-26 16',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764149192,
            insert_date: '2025-11-26 17',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764152792,
            insert_date: '2025-11-26 18',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764156392,
            insert_date: '2025-11-26 19',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764159992,
            insert_date: '2025-11-26 20',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764163592,
            insert_date: '2025-11-26 21',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764167192,
            insert_date: '2025-11-26 22',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764170792,
            insert_date: '2025-11-26 23',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764174392,
            insert_date: '2025-11-27 00',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764177992,
            insert_date: '2025-11-27 01',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764181592,
            insert_date: '2025-11-27 02',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764185192,
            insert_date: '2025-11-27 03',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764188792,
            insert_date: '2025-11-27 04',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764192392,
            insert_date: '2025-11-27 05',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764195992,
            insert_date: '2025-11-27 06',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764199592,
            insert_date: '2025-11-27 07',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764203192,
            insert_date: '2025-11-27 08',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764206792,
            insert_date: '2025-11-27 09',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764210392,
            insert_date: '2025-11-27 10',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764213992,
            insert_date: '2025-11-27 11',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764217592,
            insert_date: '2025-11-27 12',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764221192,
            insert_date: '2025-11-27 13',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
        ],
      },
    ],
    first_page_url: 'http://smartadmin.test.jiuletech.com/api/output/signEcg?page=1',
    from: 1,
    last_page: 1,
    last_page_url: 'http://smartadmin.test.jiuletech.com/api/output/signEcg?page=1',
    next_page_url: null,
    path: 'http://smartadmin.test.jiuletech.com/api/output/signEcg',
    per_page: '3',
    prev_page_url: null,
    to: 3,
    total: 3,
  },
  message: '获取成功',
}

//
export const hrOptions = {
  xAxis: {
    type: 'category',
    data: [],
    show: false,
    boundaryGap: false,
    axisLabel: {
      fontSize: getRem(12),
    },
  },
  yAxis: {
    type: 'value',
    show: false,
    min: -20,
    max: 250,
  },
  grid: {
    top: 0,
    left: 20,
    right: 20,
    bottom: 0
  },
  series: [
    {
      data: [], // 示例心率数据
      type: 'line',
      smooth: false, // 平滑曲线
      symbol: 'circle',
      // zlevel: 1,
      label: {
        show: true,
        position: 'top',
        offset: [0, 5],
        fontSize: getRem(12),
        color: '#5BDD56',
        fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        // fontStyle: 'normal',
      },
      itemStyle: {
        color: '#5BDD56',
      },
      lineStyle: {
        color: '#5BDD56', // 线条颜色
        width: getRem(2),
      },
      markLine: {
        z: 1,
        lineStyle: {
          color: '#314349',
          type: 'dashed',
        },
        symbol: ['none', 'none'],
        label: { show: false },
        data: [],
      },
      markPoint: {
        data: [],
        symbol: 'circle',
        symbolSize: '8',
        label: {
          show: true,
          borderRadius: 2,
          backgroundColor: '#DA4343',
          padding: [getRem(3), getRem(4), getRem(1), getRem(4)],
          position: 'top',
          fontSize: getRem(12),
          color: '#fff',
          fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        },
        itemStyle: {
          color: '#DA4343',
        },
      },
    },
  ],
  backgroundColor: 'transparent',
}



//
export const newOption = {
  xAxis: {
    type: 'category',
    interval:2,
    data: [],
    show: true,
    boundaryGap: true,
    axisLabel: {
      fontSize: getRem(12),
    },
  },
   yAxis: {
        type: 'value',
        min: -10,
        max: 1800,
        // 添加区间分割线
        splitLine: {
            show: false,
            lineStyle: {
                type: 'dashed'
            }
        },
        // 标记区间边界
        axisLabel: {
          show:false
        }
    },
    
  grid: {
    show:true,
    borderColor:"#384951",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0
  },
  series: [
    {
      data: [], // 示例心率数据
      type: 'line',
      smooth: false, // 平滑曲线
      symbol: 'circle',
       symbolSize: getRem(4),
      // zlevel: 1,
      label: {
        show: true,
        position: 'top',
        offset: [0, 5],
        fontSize: getRem(12),
        color: '#5BDD56',
        fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        // fontStyle: 'normal',
      },
      itemStyle: {
        color: '#5BDD56',
      },
      lineStyle: {
        color: '#5BDD56', // 线条颜色
        width: getRem(1),
      },
      markLine: {
        z: 1,
        lineStyle: {
          color: '#314349',
          type: 'dashed',
        },
        symbol: ['none', 'none'],
        label: { show: false },
        data: [],
      },
      markPoint: {
        data: [],
        symbol: 'circle',
         symbolSize: getRem(4),
        label: {
          show: true,
          borderRadius: 2,
          backgroundColor: '#DA4343',
          padding: [getRem(3), getRem(4), getRem(1), getRem(4)],
          position: 'top',
          fontSize: getRem(10),
          color: '#fff',
          fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        },
        itemStyle: {
          color: '#DA4343',
        },
      },
    },
    {
      data: [], 
      type: 'line',
      smooth: false, 
      symbol: 'circle',
       symbolSize: getRem(4),
      label: {
        show: true,
        position: 'top',
        offset: [0, 5],
        fontSize: getRem(12),
        color: '#56E3E1',
        fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
      },
      itemStyle: {
        color: '#56E3E1',
      },
      lineStyle: {
        color: '#56E3E1', // 线条颜色
        width: getRem(1),
      },
      markLine: {
        z: 1,
        lineStyle: {
          color: '#314349',
          type: 'dashed',
        },
        symbol: ['none', 'none'],
        label: { show: false },
        data: [],
      },
      markPoint: {
        data: [],
        symbol: 'circle',
        symbolSize: getRem(4),
        label: {
          show: true,
          borderRadius: 2,
          backgroundColor: '#DA4343',
          padding: [getRem(3), getRem(4), getRem(1), getRem(4)],
          position: 'top',
          fontSize: getRem(12),
          color: '#fff',
          fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        },
        itemStyle: {
          color: '#DA4343',
        },
      },
    },
    {
      data: [],
      type: 'line',
      smooth: false,
      symbol: 'circle',
       symbolSize: getRem(4),
      markLine: {
        z: 1,
        lineStyle: {
          color: '#314349',
          type: 'dashed',
        },
        symbol: ['none', 'none'],
        label: { show: false },
        data: [],
      },
      label: {
        show: true,
        position: 'top',
        offset: [0, getRem(5)],
        fontSize: getRem(12),
        color: '#D8D8D8',
        fontStyle: 'normal',
        fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',

      },
      itemStyle: {
        color: '#D8D8D8',
      },
      lineStyle: {
        color: '#D8D8D8', // 线条颜色
        width: getRem(1),
      },
      markPoint: {
        data: [],
        symbol: 'circle',
        symbolSize: getRem(4),
        label: {
          show: true,
          // offset: [0, getRem(5)],
          borderRadius: getRem(2),
          backgroundColor: '#DA4343',
          padding: [getRem(3), getRem(4), getRem(1), getRem(4)],
          position: 'top',
          fontSize: getRem(12),
          color: '#fff',
          fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        },
        itemStyle: {
          color: '#DA4343',
        },
      },
    },
    {
      data: [],
      type: 'line',
      smooth: false,
      symbol: 'circle',
       symbolSize: getRem(4),
      label: {
        show: true,
        distance: 0,
        position: 'top',
        fontSize: getRem(12),
        color: '#D8D8D8',
        fontStyle: 'normal',
        fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
      },
      markLine: {
        z: 1,
        lineStyle: {
          dashOffset: getRem(20),
          align: 'left',
          color: '#314349',
          type: 'dashed',
        },
        symbol: ['none', 'none'],
        label: { show: false },
        data: [],
      },
      itemStyle: {
        color: '#D8D8D8',
      },
      lineStyle: {
        color: '#D8D8D8', // 线条颜色
        width: getRem(1),
      },
      markPoint: {
        data: [],
        symbol: 'circle',
        symbolSize: getRem(4),
        label: {
          show: true,
          offset: [0, 0],
          borderRadius: 2,
          backgroundColor: '#DA4343',
          padding: [getRem(3), getRem(4), getRem(1), getRem(4)],
          position: 'top',
          fontSize: getRem(12),
          color: '#fff',
          fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        },
        itemStyle: {
          color: '#DA4343',
        },
      },
    }
  ],
  backgroundColor: 'transparent',
}


export const emptyOptions = {
  xAxis: {
    type: 'category',
    data: ["07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00"],
    show: true,
    boundaryGap: true,
 
    axisLine:{
      show:false
    },
    axisLabel: {
      fontSize: getRem(12)
    },
  },
  yAxis: {
    type: 'value',
    show: false,    
  },
  grid: {
    show:true,
    borderColor:"#384951",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    
  },
  series: [
    {
      data: Array.from({ length: 12 }).map(() => 0),
      type: 'line',
      smooth: false, 
      symbol: 'none',
      // zlevel: 1,
      label: {
        show: false,
        position: 'top',
        offset: [0, 5],
        fontSize: getRem(12),
        color: '#5BDD56',
        fontStyle: 'normal',
        fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
      },
      itemStyle: {
        color: '#5BDD56',
      },
      lineStyle: {
        color: '#5BDD56', // 线条颜色
        width: getRem(0),
      },
     markLine: {
        silent: true,
        symbol: 'none',
        lineStyle: {
            type: 'dashed',
            color: '#384951'
        },
        data: [
            // 在每个数据点添加垂直线
            ...Array.from({ length: 24 }).map((_, index) => ({
                xAxis: index,
                label: { show: false }
            }))
        ]
    }
    },
  ],
  backgroundColor: 'transparent',
}

export const spoOptions = {
  xAxis: {
    type: 'category',
    data: [],
    show: false, // 隐藏X轴
    boundaryGap: false,
    axisLabel: {
      color: '#BDCBD1',
      fontSize: getRem(12),
      align: 'center',
    },
  },
  yAxis: {
    type: 'value',
    show: false,
    min: -20,
    max: 200,
  },
  grid: {
    top: 0,
    left: 20,
    right: 20,
    bottom: 0,
    containLabel: true,
  },
  series: [
    {
      data: [], // 示例心率数据
      type: 'line',

      smooth: false, // 平滑曲线
      symbol: 'circle', // 不显示数据点标记
      label: {
        show: true,
        position: 'top',
        offset: [0, 5],
        fontSize: getRem(12),
        color: '#56E3E1',
        fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
      },
      itemStyle: {
        color: '#56E3E1',
      },
      lineStyle: {
        color: '#56E3E1', // 线条颜色
        width: getRem(2),
      },
      markLine: {
        z: 1,
        lineStyle: {
          color: '#314349',
          type: 'dashed',
        },
        symbol: ['none', 'none'],
        label: { show: false },
        data: [],
      },
      markPoint: {
        data: [],
        symbol: 'circle',
        symbolSize: '8',
        label: {
          show: true,
          borderRadius: 2,
          backgroundColor: '#DA4343',
          padding: [getRem(3), getRem(4), getRem(1), getRem(4)],
          position: 'top',
          fontSize: getRem(12),
          color: '#fff',
          fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        },
        itemStyle: {
          color: '#DA4343',
        },
      },
    },
  ],
  backgroundColor: 'transparent',
}

export const NibpOptions = {
  xAxis: {
    type: 'category',
    data: [],
    show: true,
    boundaryGap: false,
    axisLine: {
      show: false,
    },
    axisLabel: {
      color: '#BDCBD1',
      fontSize: getRem(12)
    },
  },
  yAxis: {
    type: 'value',
    show: false,
    min: -20,
    max: 150,
  },
  grid: {
    show:true,
    borderColor:"#384951",
    top: 0,
    left: 20,
    right: 20,
    bottom: 0,
    contain: true
  },
  series: [
    {
      data: [],
      type: 'line',
      smooth: false,
      symbol: 'circle',
      markLine: {
        z: 1,
        lineStyle: {
          color: '#314349',
          type: 'dashed',
        },
        symbol: ['none', 'none'],
        label: { show: false },
        data: [],
      },
      label: {
        show: true,
        position: 'top',
        offset: [0, getRem(5)],
        fontSize: getRem(12),
        color: '#D8D8D8',
        fontStyle: 'normal',
        fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',

      },
      itemStyle: {
        color: '#D8D8D8',
      },
      lineStyle: {
        color: '#D8D8D8', // 线条颜色
        width: getRem(2),
      },
      markPoint: {
        data: [],
        symbol: 'circle',
        symbolSize: '8',
        label: {
          show: true,
          offset: [0, getRem(5)],
          borderRadius: getRem(2),
          backgroundColor: '#DA4343',
          padding: [getRem(3), getRem(4), getRem(1), getRem(4)],
          position: 'top',
          fontSize: getRem(12),
          color: '#fff',
          fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        },
        itemStyle: {
          color: '#DA4343',
        },
      },
    },
    {
      data: [],
      type: 'line',
      smooth: false,
      symbol: 'circle',
      label: {
        show: true,
        position: 'bottom',
        fontSize: getRem(12),
        color: '#D8D8D8',
        fontStyle: 'normal',
        fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
      },
      markLine: {
        z: 1,
        lineStyle: {
          dashOffset: getRem(20),
          align: 'left',
          color: '#314349',
          type: 'dashed',
        },
        symbol: ['none', 'none'],
        label: { show: false },
        data: [],
      },
      itemStyle: {
        color: '#D8D8D8',
      },
      lineStyle: {
        color: '#D8D8D8', // 线条颜色
        width: getRem(2),
      },
      markPoint: {
        data: [],
        symbol: 'circle',
        symbolSize: getRem(8),
        label: {
          show: true,
          offset: [0, 0],
          borderRadius: 2,
          backgroundColor: '#DA4343',
          padding: [getRem(3), getRem(4), getRem(1), getRem(4)],
          position: 'bottom',
          fontSize: getRem(12),
          color: '#fff',
          fontStyle: 'normal',
          fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
        },
        itemStyle: {
          color: '#DA4343',
        },
      },
    }
  ],
  backgroundColor: 'transparent',
}
