export const baseMenuList = [
        {
            name:"患者管理",
            path:"/home/patientManagement",
            child:[{
                name:"患者列表",
                path:"/home/patientManagement"
            },
            {
                name:"佩戴统计",
                path:"/wardOverview/wearingSituationManagement"
            },
            {
                name:"主动随访",
                path:"/researchfollowup/activefollowup"
            },{
                name:"脱组记录",
                path:"/researchfollowup/groupRemovalRecord"
            },{
                 name:"患者信息",
                 hidden:true
            },{
                 name:"病程管理",
                 hidden:true
            }
        ]
        },{
            name:"设备管理",
            path:"/wardOverview/equipmentManagement",
             child:[{
                name:"穿戴监护",
                path:"/wardOverview/device"
            },
            {
                name:"血糖监护",
                path:"/wardOverview/sugerDevice"
            }]
        },{
            name:"医嘱管理",
            path:"/researchfollowup/medicalorder",
            child:[
            {
                name:"用药计划",
                path:"/researchfollowup/medicalorder"
            },{
                name:"护理记录",
                path:"/nursingEventRecord/index"
          }]
        },{
            name:"康复管理",
            path:"/patientEducation/index",
             child:[
            {
                name:"康复运动记录",
                path:"/rehabilitationTraining/rehabilitationTrainingplan"
            },{
                name:"呼吸训练记录",
                path:"/rehabilitationTraining/breathingTraining"
          }]
        },{
            name:"监测中心",
            path:"/healthAnalysis",
             child:[
            {
                name:"病区活动总览",
                path:"/healthAnalysis/wardMovementAnalysis"
            },{
                name:"病区血糖总览",
                path:"/overviewofBlood/index"
          }]
        },{
            name:"监测计划",
            path:"/electrocardiogramMonitoring",
            child:[
            {
                name:"心电监测计划",
                path:"/electrocardiogramMonitoring/electrocardiogramMonitoringplan"
            },{
                name:"血压监测计划",
                path:"/bloodpressuremonitoring/bloodpressuremonitoringplan"
          }]
        }]

export const baseScreenMenuList = [{
            name:"监护总览",
            path:"/monitoringOverview",
            child:[]
        },{
            name:"监护分析",
            path:"/monitoringandanalysis",
            child:[]
        },{
            name:"血压记录",
            path:"/electrocardiogramMonitoring/bloodPressureRecord",
            child:[]
        },{
            name:"心电记录",
            path:"/electrocardiogramMonitoring/electrocardiogramMonitoringplannew",
            child:[]
        },{
            name:"HRV分析",
            path:"/rightAside/hrv",
            child:[]
        },{
            name:"血糖分析",
            path:"/bloodSugarAnalysis/index",
            child:[]
        },{
            name:"睡眠分析",
            path:"/rightAside/sleep",
            child:[]
        },{
            name:"活动事件",
            path:"/rightAside/activity_inner",
            child:[]
        },{
            name:"活动报告",
            path:"/patientMovementAnalysis/index",
            child:[]
        }];