import { getRem,scaleByHeight } from '@/utils/function/function'
export const mockDataScreen = {
  status: '200',
  result: {
    current_page: 1,
    data: [
      {
        ccid: 'JL2100EF54917F100E49',
        high_heartrate_value: 130,
        low_heartrate_value: 40,
        spo2: 92,
        patient_id: 2,
        name: '123444',
        bed_number: '002',
        bat: 21,
        bind_time: 1760943565,
        bind_date: '2025/10/20 14:59 绑定',
        list: [
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764138392,
            insert_date: '2025-11-26 14',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764141992,
            insert_date: '2025-11-26 15',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764145592,
            insert_date: '2025-11-26 16',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764149192,
            insert_date: '2025-11-26 17',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764152792,
            insert_date: '2025-11-26 18',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764156392,
            insert_date: '2025-11-26 19',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764159992,
            insert_date: '2025-11-26 20',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764163592,
            insert_date: '2025-11-26 21',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764167192,
            insert_date: '2025-11-26 22',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764170792,
            insert_date: '2025-11-26 23',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764174392,
            insert_date: '2025-11-27 00',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764177992,
            insert_date: '2025-11-27 01',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764181592,
            insert_date: '2025-11-27 02',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764185192,
            insert_date: '2025-11-27 03',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764188792,
            insert_date: '2025-11-27 04',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764192392,
            insert_date: '2025-11-27 05',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764195992,
            insert_date: '2025-11-27 06',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764199592,
            insert_date: '2025-11-27 07',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764203192,
            insert_date: '2025-11-27 08',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764206792,
            insert_date: '2025-11-27 09',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764210392,
            insert_date: '2025-11-27 10',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764213992,
            insert_date: '2025-11-27 11',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764217592,
            insert_date: '2025-11-27 12',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764221192,
            insert_date: '2025-11-27 13',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
        ],
      },
      {
        ccid: 'JL2B07E8E56B58D07E37',
        high_heartrate_value: 130,
        low_heartrate_value: 40,
        spo2: 92,
        patient_id: 5,
        name: 'dasda',
        bed_number: '003',
        bat: 91,
        bind_time: 1762331543,
        bind_date: '2025/11/05 16:32 绑定',
        list: [
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764138392,
            insert_date: '2025-11-26 14',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764141992,
            insert_date: '2025-11-26 15',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764145592,
            insert_date: '2025-11-26 16',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764149192,
            insert_date: '2025-11-26 17',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764152792,
            insert_date: '2025-11-26 18',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764156392,
            insert_date: '2025-11-26 19',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764159992,
            insert_date: '2025-11-26 20',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764163592,
            insert_date: '2025-11-26 21',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764167192,
            insert_date: '2025-11-26 22',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764170792,
            insert_date: '2025-11-26 23',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764174392,
            insert_date: '2025-11-27 00',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764177992,
            insert_date: '2025-11-27 01',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764181592,
            insert_date: '2025-11-27 02',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764185192,
            insert_date: '2025-11-27 03',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764188792,
            insert_date: '2025-11-27 04',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764192392,
            insert_date: '2025-11-27 05',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764195992,
            insert_date: '2025-11-27 06',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764199592,
            insert_date: '2025-11-27 07',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764203192,
            insert_date: '2025-11-27 08',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764206792,
            insert_date: '2025-11-27 09',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764210392,
            insert_date: '2025-11-27 10',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764213992,
            insert_date: '2025-11-27 11',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764217592,
            insert_date: '2025-11-27 12',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764221192,
            insert_date: '2025-11-27 13',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
        ],
      },
      {
        ccid: 'JL2E7D07BB3E47B7D888',
        high_heartrate_value: 130,
        low_heartrate_value: 40,
        spo2: 92,
        patient_id: 58,
        name: 'zc_test1',
        bed_number: null,
        bat: null,
        bind_time: 1764034846,
        bind_date: '2025/11/25 09:40 绑定',
        list: [
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764138392,
            insert_date: '2025-11-26 14',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764141992,
            insert_date: '2025-11-26 15',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764145592,
            insert_date: '2025-11-26 16',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764149192,
            insert_date: '2025-11-26 17',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764152792,
            insert_date: '2025-11-26 18',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764156392,
            insert_date: '2025-11-26 19',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764159992,
            insert_date: '2025-11-26 20',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764163592,
            insert_date: '2025-11-26 21',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764167192,
            insert_date: '2025-11-26 22',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764170792,
            insert_date: '2025-11-26 23',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764174392,
            insert_date: '2025-11-27 00',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764177992,
            insert_date: '2025-11-27 01',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764181592,
            insert_date: '2025-11-27 02',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764185192,
            insert_date: '2025-11-27 03',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764188792,
            insert_date: '2025-11-27 04',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764192392,
            insert_date: '2025-11-27 05',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764195992,
            insert_date: '2025-11-27 06',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764199592,
            insert_date: '2025-11-27 07',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764203192,
            insert_date: '2025-11-27 08',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764206792,
            insert_date: '2025-11-27 09',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764210392,
            insert_date: '2025-11-27 10',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764213992,
            insert_date: '2025-11-27 11',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764217592,
            insert_date: '2025-11-27 12',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
          {
            is_num: 0,
            spo2: 0,
            heartrate: 0,
            insert_time: 1764221192,
            insert_date: '2025-11-27 13',
            spo2_type: 0,
            high_heartrate_type: 0,
            low_heartrate_type: 0,
          },
        ],
      },
    ],
    first_page_url: 'http://smartadmin.test.jiuletech.com/api/output/signEcg?page=1',
    from: 1,
    last_page: 1,
    last_page_url: 'http://smartadmin.test.jiuletech.com/api/output/signEcg?page=1',
    next_page_url: null,
    path: 'http://smartadmin.test.jiuletech.com/api/output/signEcg',
    per_page: '3',
    prev_page_url: null,
    to: 3,
    total: 3,
  },
  message: '获取成功',
}

export const respiratoryOptions = {
  xAxis: {
    type: 'category',
    axisLine:{
      lineStyle:{
         color:"#eeeeee"
      }
    },
    axisLabel: {
      fontSize: scaleByHeight(12),
      color:"#929FAF"
    },
    data: [
      '17.20',
      '17:30',
      '17:40',
      '17:50',
      '18:00',
      '18:10',
      '18:20',
      '18:30',
      '18:40',
      '18:50',
      '19:00',
      '19:10',
      '19:20',
    ],
    show: true,
    axisTick: {
      show: false,
    },
    boundaryGap: true,
  },
  yAxis: {
    type: 'value',
    show: true,
    min: 0,
    max: (value: any) => {
    const num = value.max || 20;
    return num ? ( num + 10) -(num + 10)%5 : 20
   },
    splitLine: {
      show: true,
      lineStyle: {
        color: '#eeeeee',
      },
    },
    axisLabel: {
      show: false,
    },
    axisLine: {
      show: false,
    },
  },
  color: {
    type: 'linear',
    x: 0,
    y: 0,
    x2: 0,
    y2: 1,
    colorStops: [
      {
        offset: 0.2,
        color: '#5ADBB4', // 0% 处的颜色
      },
      {
        offset: 1,
        color: '#24B287', // 100% 处的颜色
      },
    ],
    global: false, // 缺省为 false
  },
  grid: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  tooltip: {
    trigger: 'axis',
    show: true,
  },
  series: [
    {
      data: [30, 10, 30, 40, 10, 20, 30, 40, 10, 70, 10, 20, 30],
      label:{
        fontSize:getRem(12),
         show: true,           
            position: 'top',    
            color:"#24B287",  
            formatter: (e:any)=>{
              if(e.value == 0){
                  return ""
              }
               return e.value
 
            }
      },
      type: 'bar',
      barWidth: 16,
      backgroundStyle: {
        color: '',
      },
      lineStyle: {
        color: '#24B287', // 线条颜色
        width: getRem(2),
      },
    },
  ],
  backgroundColor: 'transparent',
}

//
export const hrOptions = {
  xAxis: {
    type: 'category',
    data: [],
    show: true,
    axisLine:{
       lineStyle:{
         color:"#EEEEEE"
       }
    },
    axisLabel: {
      // interval: 1,
      color:"#929FAF",
      fontSize: scaleByHeight(12),
      margin:4
    },
    axisTick: {
      show: false,
    },
    boundaryGap: true,
  },
  yAxis: {
    type: 'value',
    show: false,
    min: 0,
    max: 220,
  },
  grid: {
    top: getRem(20),
    left: 0,
    right: "2%",
    bottom: 0,
    // clip: false,
  },
  series: [
    {
      data: [],  
      type: 'line',
      smooth: false, 
      symbol: 'circle', 
      symbolSize: 8, 
      label: {
        show: false,
        distance:0,
        position: 'top',
        fontSize: scaleByHeight(12),
        color: '#24B287',
        fontStyle: 'normal',
        fontFamily: '"Alibaba PuHuiTi 3.0", "Alibaba PuHuiTi 30"',
      },
      itemStyle: {
         borderWidth:scaleByHeight(2),
          borderColor:"#ffffff",
        color: '#24B287',
      },
      lineStyle: {
        color: '#24B287', // 线条颜色
        width:scaleByHeight(1.5),
      },

      markPoint: {
        data: [],
        symbol: 'circle',
        symbolSize: '8',
        label: {
          show: true,
        },
        itemStyle: {
     
        },
      },
       markArea: {
            silent: true,           // 是否不响应鼠标事件
            label: {
                show: false,
                position: ['50%'],       // 标签位置
            },
            itemStyle: {
                color: '#EAFFF9',          // 区域颜色
                opacity: 1         // 透明度
            },
            data: [[{
                        yAxis: 40,
                        itemStyle: {
                            color: '#EAFFF9'
                        }
                    },
                    {
                        yAxis: 130
                    }]]                 // 区域数据
        }
    },
  ],
  backgroundColor: 'transparent',
}

export const spoOptions = {
  xAxis: {
    type: 'category',
    data: [],
    show: true,
   
      axisLine:{
       lineStyle:{
         color:"#EEEEEE"
       }
    },
    axisLabel: {
      interval: 1,
      color:"#929FAF",
      fontSize: scaleByHeight(12),
      margin:4
    },
    axisTick: {
      show: false,
    },
    boundaryGap: false,
  },
  yAxis: {
    type: 'value',
    show: false,
    min: 0,
    max: 220,
  },
  grid: {
    top: getRem(20),
    left: 0,
    right: "2%",
    bottom: 0,
  },
  series: [
    {
      data: [], 
      type: 'line',
      smooth: false, 
      symbol: 'circle', 
       symbolSize: '8',
      label: {
        show: false,
        position: 'top',
        fontSize: getRem(12),
        distance: 0,
        color: '#0477E0',
        fontStyle: 'normal',
        fontFamily: 'Alibaba PuHuiTi 3.0, Alibaba PuHuiTi 30',
      },
       itemStyle: {
         borderWidth:scaleByHeight(2),
          borderColor:"#ffffff",
        color: '#0477E0',
      },
      lineStyle: {
        color: '#0477E0', // 线条颜色
        width:scaleByHeight(1.5),
      },
      markLine: {
        z: 1,
        lineStyle: {
          color: '#314349',
          type: 'dashed',
        },
        symbol: ['none', 'none'],
        label: { show: false },
        data: [],
      },
      markPoint: {
        data: [],
        symbol: 'circle',
        label: {
         
        },
        itemStyle: {
          color: '#DA4343',
        },
      },
       markArea: {
            silent: true,           // 是否不响应鼠标事件
            label: {
                show: false,
                position: ['50%'],       // 标签位置
            },
            itemStyle: {
                color: '#EAFFF9',          // 区域颜色
                opacity: 1         // 透明度
            },
            data: [[{
                        yAxis: 20,
                        itemStyle: {
                            color: '#EAF4FE'
                        }
                    },
                    {
                        yAxis: 130
                    }]]                 // 区域数据
        }
    },
  ],
  backgroundColor: 'transparent',
}

type DataPoint = [number, number][]
export const electrocardiogramOptions = {
  xAxis: {
    type: 'time',
    data: <number[]>[],
    show: false,
  },
  yAxis: {
    type: 'value',
    show: false,
  },
  backgroundColor: 'transparent',
  grid: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zlevel: 99,
  },
  series: [
    {
      data: <DataPoint>[],
      type: 'line',
      smooth: true,
      color: '#FF4DA3',
      symbol: 'none',
      lineStyle: {
        width: 1,
      },
    },
  ],
  dataZoom: [
    {
      type: 'inside', //类型
      show: true, //显示
      // minValueSpan: 30 * 1000, // 最小窗口范围：1 分钟（60,000 毫秒）
      // maxValueSpan: 10 *60 *1000, // 最大窗口范围：1 分钟（固定）
      start: 90,
      end: 100,
    },
  ],
}
