/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPatient: typeof import('./components/addPatient.vue')['default']
    BaseHeader: typeof import('./components/baseHeader.vue')['default']
    BaseMenu: typeof import('./components/baseMenu.vue')['default']
    BedDetail: typeof import('./components/BedDetail.vue')['default']
    BodyData: typeof import('./components/BodyData.vue')['default']
    CustomDialog: typeof import('./components/custom-dialog.vue')['default']
    DebiceItem: typeof import('./components/debiceItem.vue')['default']
    DeviceSet: typeof import('./components/DeviceSet.vue')['default']
    DeviceSetCopy: typeof import('./components/DeviceSetCopy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElcPagination: typeof import('./components/elc-pagination.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Empty: typeof import('./components/empty.vue')['default']
    HeaderSeach: typeof import('./components/HeaderSeach.vue')['default']
    HomeIcon: typeof import('./components/HomeIcon.vue')['default']
    ListItem: typeof import('./components/listItem.vue')['default']
    ListItemV2: typeof import('./components/ListItemV2.vue')['default']
    Map: typeof import('./components/map.vue')['default']
    MyTooltip: typeof import('./components/myTooltip.vue')['default']
    NighttimeBloodOxygen: typeof import('./components/sleepcoms/nighttime-blood-oxygen.vue')['default']
    NighttimeRespiratoryRate: typeof import('./components/sleepcoms/nighttime-respiratory-rate.vue')['default']
    NursingEvents: typeof import('./components/nursingEvents.vue')['default']
    PasswordInput: typeof import('./components/passwordInput.vue')['default']
    PatientInfo: typeof import('./components/PatientInfo.vue')['default']
    PatientInfoEdit: typeof import('./components/patientInfoEdit.vue')['default']
    Rightaside: typeof import('./components/rightaside.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sleepdistribution: typeof import('./components/sleepcoms/sleepdistribution.vue')['default']
    SleepQualityAssessment: typeof import('./components/sleepcoms/sleep-quality-assessment.vue')['default']
    TabList: typeof import('./components/TabList.vue')['default']
    TotalNighttimeSleep: typeof import('./components/sleepcoms/total-nighttime-sleep.vue')['default']
    WeeklySleepStaging: typeof import('./components/sleepcoms/weekly-sleep-staging.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
