import { dateFtt } from "@/utils/date/dateFtt";
interface sleepOptionType {
    series: Array<series>,
    [key: string]: any
}
interface series {
    data: Array<number>,
    [key: string]: any
}
export const sleepOption:sleepOptionType = {
    grid: {
        left: '50',
        right: '20',
        bottom: '0',
        top: "0",
        containLabel: true
    },
    tooltip: {
        triggerOn: 'click',
        formatter: function (params:any) {
            return ''
        },
    },

    xAxis: {
        type: 'category',
        axisTick: {
            show: false
        },
        axisLabel: {
            showMinLabel: true,
            showMaxLabel: true,
            boundaryGap: 0,
            interval: 17,
            formatter: function (value:number) {
                return dateFtt('hh:MM', new Date(Number(value)))
            },
            color: "#9296AF",
        },
        axisLine: {
            lineStyle: {
                color: '#EEEEEE'
            }
        },
        axisPointer: {
            show: true,
            status: 'show',
            axis: "x",
            value: 0,
            type: 'line',
            snap: true,
            label: {
                show: false
            },
            lineStyle: {
                color: {
                    type: 'linear',
                    x: 0,
                    y: 0,
                    x2: 0,
                    y2: 1,
                    colorStops: [{
                        offset: 0, color: 'rgba(226, 64, 64, 0)' // 0% 处的颜色
                    }, {
                        offset: 1, color: 'rgba(226, 64, 64, 1)' // 100% 处的颜色
                    }],
                    global: false // 缺省为 false
                },
                type: 'solid',
                width: 2
            },
            handle: {
                show: true,
                size: 0
            }

        },
    },
    yAxis: {
        type: 'value',
        interval: 1,
        axisTick: {
            alignWithLabel: false
        },
        splitLine: {
            lineStyle: {
                color: '#EEEEEE'
            }
        },
        axisLabel: {
            color: "#9296AF",
            lineHeight: 18,
            // fontFamily: 'Source Han Sans CN-Regular',
            position: 'inside', // 将标签放置在刻度内部
            customValues: [0.5, 1.5, 2.5, 3.5],
            formatter: (value: number) => {
                // 将数值映射为文字标签
                let labels = '';
                if (value == 0.5) {
                    labels = '深度\n睡眠';
                }
                if (value == 1.5) {
                    labels = '中度\n睡眠';
                }
                if (value == 2.5) {
                    labels = '轻度\n睡眠';
                }
                if (value == 3.5) {
                    labels = '零星小睡\n或静息';
                }
                return labels;
            }
        }
    },
    series: [
        {
            name: '深度睡眠',
            type: 'bar',
            stack: 'a',
            data: [], // 数据
            barGap: '0%', // 柱体间隔为 0
            barCategoryGap: '0%', // 类目间隔为 0
            barWidth: '120%', // 设置柱体宽度为 100
            itemStyle: {
                color: function (params:any) {
                    let index = params.dataIndex,
                        color = 'transparent';
                    return color;
                }
            }
        },
        {
            name: '中度睡眠',
            type: 'bar',
            stack: 'a',
            data: [], // 数据
            itemStyle: {
                color: function (params:any) {
                    let index = params.dataIndex,
                        color = 'transparent';
                    //   if (sleep_text[index] == 9) {
                    //     color = '#9E4AE3';
                    //   } else {
                    //     color = 'transparent';
                    //   }
                    return color;
                }
            }
        },
        {
            name: '轻度睡眠',
            type: 'bar',
            stack: 'a',
            data: [], // 数据

            itemStyle: {
                color: function (params:any) {
                    let index = params.dataIndex,
                        color = 'transparent';
                    //   if (sleep_text[index] == 1) {
                    //     color = '#ED95F7';
                    //   } else {
                    //     color = 'transparent';
                    //   }
                    return color;
                }
            }
        },
        {
            name: '零星小睡',
            type: 'bar',
            stack: 'a',
            data: [], // 数据

            itemStyle: {
                color: function (params:any) {
                    let index = params.dataIndex,
                        color = 'transparent';
                    return color;
                }
            }
        }
    ]
}
// 睡眠质量评估
export const sleepPieOption = {
    color: ['#D766FF', '#8F66FF','#6674FF'],
    
    series: {
        type: 'pie',
        radius: ["60%", "100%"],
        left: 'center',
        width: '100%',
        itemStyle: {
                borderWidth: 1,       // 设置扇形边框宽度
                borderColor: '#fff'   // 设置扇形边框颜色
              },
          emphasis: {
              scale:true,
              scaleSize:0.5,
          },
        label: {
            show:false,
            alignTo: 'edge',
            formatter: '{name|{b}} {time|{c} %}\n',
            minMargin: 5,
            edgeDistance: 10,
            lineHeight: 15,
            fontSize: 14,
            rich: {
                time: {
                    fontSize: 14,
                    color: 'inherit'
                }
            }
        },
        labelLine: {
            length: 15,
            length2: 0,
            maxSurfaceAngle: 80
        },
        labelLayout: function (params: { labelRect: { x: number; width: any; }; labelLinePoints: any; }) {
        },
        data: [
            { name: '轻度睡眠', value: 0 },
            { name: '中度睡眠', value: 0 },
            { name: '深度睡眠', value: 0 },
        ]
    }
};

const time = new Date("2024/11/25 00:00:00").getTime();

export const xlOptions = {
   grid: {
        left: "0%",
        right: "4%",
        bottom: "10%",
        top: "5%",
    },
  xAxis: {
    type: 'category',
    data:<string[]>["21.35","22:00","23:00","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:12"],
      axisLabel: {
        showMinLabel: true,
        showMaxLabel: true,
         color: "#9296AF",
      },
       
      axisLine:{
         lineStyle:{
           color:"#eeeeee"
         } 
      },
     splitLine: {
            show: false,
        },
        axisTick: {
          show:false
        },
  },
  yAxis: {
    type: 'value',
     axisLabel:{
           color:"#929FAF"
        },
     splitLine: {
       color: "#EEEEEE",
      },
        axisTick: {
          show:false
        }

  },
  series: [
    {
      data: <any>[],
      itemStyle:{
        color:"#5BDD56"
      },
      symbolSize:6,
      symbol: "none",
      type: 'line',
      label: {
         show: false,
        position: 'top',   
      },
      lineStyle:{
        type:"solid",
        color:"#5BDD56",
        width:2
      },
      markPoint:{
        show:false,
        symbol: "circle",
        itemStyle:{
           color:"#5BDD56"
        }
      }
    }
  ]

}

export const xyOptions =  {
   grid: {
        left: "0%",
        right: "4%",
        bottom: "10%",
        top: "6%",
    },
  xAxis: {
    type: 'category',
    data:<string[]>[],
    axisLine:{
         lineStyle:{
           color:"#eeeeee"
         } 
      },
      axisLabel: {
        showMinLabel: true,
        showMaxLabel: true,
          color: "#9296AF"
      },
     splitLine: {
            show: false,
        },
        axisTick: {
          show:false
        },
  },
  yAxis: {
    type: 'value',
      min:70,
       axisLabel:{
           color:"#929FAF"
        },
     splitLine: {
       color: "#EEEEEE",
      },
        axisTick: {
          show:false
        }

  },
  series: [
    {
      data: <any>[],
      itemStyle:{
        color:"#56E3E1"
      },
    
      symbolSize:6,
      symbol: "none",
      type: 'line',
      label: {
        show: false,          // 显示数字
        position: 'top',     // 数字位置
      },
       
      lineStyle:{
        type:"solid",
        color:"#56E3E1",
        width:2
      }
    }
  ]

}


export const hxOptions = {
   grid: {
        left: "0%",
        right: "4%",
        bottom: "10%",
        top: "8%",
    },
  xAxis: {
    type: 'category',
    data:<string[]>[],
    axisLine:{
       lineStyle:{
           color:"#EEEEEE"
       }
    },
     axisLabel: {
            color: "#9296AF",
          },
     splitLine: {
            show: false,
        },
        axisTick: {
          show:false
        },
  },
  yAxis: {
    type: 'value',
    axisLabel:{
           color:"#929FAF"
        },
     splitLine: {
       color: "#EEEEEE",
      },
        axisTick: {
          show:false
        }

  },
  series: [
    {
      data: <any>[],
      itemStyle:{
        color:"#8F66FF"
      },
      symbolSize:6,
      symbol: "circle",
      type: 'line',
      label: {
        show: true,          // 显示数字
        offset:[0,5],
        position: 'top',     // 数字位置
        // 自定义格式示例：
        // formatter: function(params) {
        //   return params.value + ' 单位'; // 添加单位
        // }
      },
      lineStyle:{
        type:"solid",
        color:"#8F66FF",
        width:2
      },
      markPoint:{
        symbol: "circle",
        itemStyle:{
           color:"#8F66FF"
        }
      }
    }
  ]

}


export const sleepOptions = {
    tooltip: {
        backgroundColor: "rgba(0,0,0,.7)"
    },
    grid: {
        left: "8%",
        right: "4%",
        bottom: "10%",
        top: "5%",
    },
    xAxis: {
        type: "value",
        max: 144,
        min: 0,
        interval: 24,
        axisLabel: {
            color: "#9296AF",
            formatter: (params: any) => {
                // console.log(params);
                return dateFtt("hh:MM", new Date(params * 600000 + time));
            },
        },
        splitLine: {
            show: false,
        },
        axisTick: {
            //x轴刻度相关设置
            alignWithLabel: true,
        },
    },
    formatter: (params: any) => { },
    yAxis: {
        type: "category",
        data: <any[]>[],
        axisLabel:{
           color:"#929FAF"
        },
        splitLine: {
            show: false,
        },
         nameGap:10,
        axisLine: {
            show: false,
        },
        axisTick: {
            show: false,
        },
        zlevel: 2,
    },
    series: <any[]>[]
}


export const sleepBarOption = {
  "state": 200,
  "info": {
    "sleep_score": 89,
    "sleep_tips": "一般",
    "total_sleep_time": 7.5,
    "total_sleep_time_min": 450,
    "real_sleep_time": 6.3,
    "max_deep_sleep": 0.7,
    "light_sleep_time": 2,
    "mid_sleep_time": 1.8,
    "deep_sleep_time": 2.5,
    "in_sleep_time_info": "11/24 22:47",
    "out_sleep_time_info": "11/25 06:17",
    "insleep_time": "2025-11-24 22:47:59",
    "outsleep_time": "2025-11-25 06:17:59",
    "report_insleep_time": "22:47",
    "report_outsleep_time": "06:17",
    "risk_of_snoring": "中风险",
    "night_sleep_text": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      3,
      7,
      10,
      10,
      10,
      10,
      6,
      8,
      6,
      9,
      9,
      7,
      9,
      10,
      10,
      10,
      8,
      8,
      9,
      10,
      9,
      8,
      7,
      10,
      8,
      7,
      10,
      10,
      10,
      9,
      10,
      8,
      7,
      8,
      9,
      9,
      10,
      7,
      9,
      8,
      9,
      9,
      7,
      8,
      1,
      10,
      4,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "night_sleep_start": 22,
    "night_sleep_end": 67,
    "night_sleeping_heartrate": {
      "night_sleep_hr_text": {
        "23:00": 81,
        "23:10": 73,
        "23:20": 68,
        "23:30": 69,
        "23:40": 72,
        "23:50": 70,
        "00:00": 63,
        "00:10": 57,
        "00:40": 71,
        "00:50": 65,
        "01:00": 67,
        "01:10": 64,
        "01:20": 65,
        "01:30": 67,
        "01:40": 68,
        "01:50": 64,
        "02:00": 74
      },
      "max_hr": 81,
      "min_hr": 57,
      "avg_hr": 68,
      "sd_hr": 5.2
    },
    "night_sleeping_spo2": {
      "night_sleep_spo2_text": {
        "23:00": 93,
        "23:10": 98,
        "23:20": 96,
        "23:30": 99,
        "23:40": 94,
        "23:50": 96,
        "00:00": 99,
        "00:10": 99,
        "00:40": 98,
        "00:50": 99,
        "01:00": 99,
        "01:10": 98,
        "01:20": 99,
        "01:30": 99,
        "01:40": 96,
        "01:50": 99,
        "02:00": 96
      },
      "max_spo2": 99,
      "min_spo2": 93,
      "avg_spo2": 97,
      "sd_spo2": 1.9
    },
    "deep_sleep_time_per": 39.7,
    "mid_sleep_time_per": 28.6,
    "light_sleep_time_per": 31.7,
    "deep_sleep_info": "偏高",
    "mid_sleep_info": "正常",
    "light_sleep_info": "偏低",
    "sleep_hr_health_score": 100,
    "sleep_spo2_health_score": 100,
    "compare_flag": {
      "compare_osahs": {
        "flag": -1
      },
      "compare_hr_health": {
        "flag": 0
      },
      "compare_spo2_health": {
        "flag": 0
      },
      "compare_deep_sleep": {
        "flag": 0
      },
      "compare_mid_sleep": {
        "flag": 0
      },
      "compare_light_sleep": {
        "flag": 0
      }
    },
    "risk_result_tips": {
      "deep_sleep_tips": {
        "risk": "深度睡眠比例偏高",
        "info": "您的深度睡眠比例为39.7%，高于正常范围15%~25%。您的深度睡眠比例高于正常范围，通常是一个好的迹象，表明您的身体得到了充分的恢复。不过，如果您感到白天仍然疲倦，可能需要关注其他睡眠阶段的比例。"
      },
      "mid_sleep_tips": {
        "risk": "",
        "info": "您的中度睡眠比例为28.6%，处于正常范围25%~40%。"
      },
      "light_sleep_tips": {
        "risk": "轻度睡眠比例偏低",
        "info": "您的轻度睡眠比例为31.7%，低于正常范围45%~65%。轻度睡眠是睡眠的初始阶段，比例过低可能意味着您直接进入了较深的睡眠阶段，这可能是由于过度疲劳所致。建议您睡前1小时避免使用电子设备；限制咖啡因和酒精摄入"
      },
      "osahs_sleep_tips": {
        "risk": "睡眠呼吸暂停风险中风险",
        "info": "您的睡眠呼吸暂停风险为中风险。睡眠呼吸暂停可能会影响您的睡眠质量，导致白天嗜睡、注意力不集中等问题。建议您侧卧睡眠，减少舌根后坠，缓解气道阻塞；同时也建议您戒酒以及避免镇静类药物，摄入这些会松弛咽部肌肉加重阻塞。"
      },
      "total": "睡眠好。睡眠状况良好，加油！"
    }
  },
  "sleep_draw_pic_info": {
    "sleep_range": {
      "0": {
        "date": "2025-11-21",
        "in_sleep_index": 142,
        "out_sleep_index": 143,
        "in_sleep_time": "23:41",
        "out_sleep_time": "",
        "temp_date": "20251121"
      },
      "1": {
        "date": "2025-11-22",
        "in_sleep_index": 0,
        "out_sleep_index": 26,
        "in_sleep_time": "",
        "out_sleep_time": "04:29",
        "temp_date": "20251122"
      },
      "2": {
        "date": "2025-11-22",
        "in_sleep_index": 139,
        "out_sleep_index": 143,
        "in_sleep_time": "23:11",
        "out_sleep_time": "",
        "temp_date": "20251122"
      },
      "3": {
        "date": "2025-11-23",
        "in_sleep_index": 0,
        "out_sleep_index": 35,
        "in_sleep_time": "",
        "out_sleep_time": "05:59",
        "temp_date": "20251123"
      },
      "4": {
        "date": "2025-11-23",
        "in_sleep_index": 136,
        "out_sleep_index": 143,
        "in_sleep_time": "22:47",
        "out_sleep_time": "",
        "temp_date": "20251123"
      },
      "5": {
        "date": "2025-11-24",
        "in_sleep_index": 0,
        "out_sleep_index": 37,
        "in_sleep_time": "",
        "out_sleep_time": "06:11",
        "temp_date": "20251124"
      },
      "6": {
        "date": "2025-11-24",
        "in_sleep_index": 136,
        "out_sleep_index": 143,
        "in_sleep_time": "22:47",
        "out_sleep_time": "",
        "temp_date": "20251124"
      },
      "7": {
        "date": "2025-11-25",
        "in_sleep_index": 0,
        "out_sleep_index": 37,
        "in_sleep_time": "",
        "out_sleep_time": "06:17",
        "temp_date": "20251125"
      }
    },
    "sleep_draw": {
      "2025-11-25": [
        8,
        6,
        9,
        9,
        7,
        9,
        10,
        10,
        10,
        8,
        8,
        9,
        10,
        9,
        8,
        7,
        10,
        8,
        7,
        10,
        10,
        10,
        9,
        10,
        8,
        7,
        8,
        9,
        9,
        10,
        7,
        9,
        8,
        9,
        9,
        7,
        8,
        1,
        10,
        4,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "2025-11-24": [
        10,
        10,
        7,
        8,
        10,
        10,
        9,
        7,
        10,
        10,
        10,
        7,
        9,
        9,
        10,
        8,
        8,
        10,
        9,
        10,
        9,
        9,
        7,
        8,
        7,
        10,
        9,
        9,
        10,
        10,
        7,
        9,
        7,
        9,
        7,
        10,
        9,
        101,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        7,
        10,
        10,
        10,
        10,
        6
      ],
      "2025-11-23": [
        10,
        9,
        9,
        9,
        9,
        9,
        9,
        10,
        10,
        10,
        10,
        9,
        9,
        9,
        8,
        9,
        10,
        10,
        8,
        9,
        9,
        9,
        6,
        3,
        9,
        8,
        10,
        10,
        9,
        8,
        0,
        0,
        8,
        9,
        9,
        7,
        101,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        6,
        8,
        10,
        10,
        10,
        10,
        8
      ],
      "2025-11-22": [
        10,
        10,
        10,
        10,
        9,
        9,
        10,
        10,
        7,
        8,
        10,
        10,
        10,
        8,
        9,
        9,
        10,
        10,
        9,
        8,
        9,
        9,
        9,
        10,
        8,
        10,
        10,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        4,
        4,
        10,
        10,
        10,
        9
      ],
      "2025-11-21": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        7,
        6,
        0,
        0,
        0,
        0,
        1,
        1,
        7,
        0,
        5,
        10
      ],
      "2025-11-20": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "2025-11-19": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  }
}

